github:
  description: "Apache Grails Website"
  homepage: https://grails.apache.org/
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "*.x"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
