:gradle: http://www.gradle.org
:markupte: http://docs.groovy-lang.org/latest/html/documentation/markup-template-engine.html

= Grails Website

Grails is a powerful web framework, for the Java platform
aimed at multiplying developers’ productivity thanks to a Convention-over-Configuration, sensible defaults 
and opinionated APIs. It integrates smoothly with the JVM, allowing you to be immediately productive whilst
providing powerful features, including integrated ORM, Domain-Specific Languages,
runtime and compile-time meta-programming and Asynchronous programming.


== Sources for the Grails website

This project builds the Grails website. It is using {gradle}[Gradle] and is fully statically generated.

Build is image:https://travis-ci.org/grails/grails-static-website.svg?branch=master["Build Status", link="https://travis-ci.org/grails/grails-static-website"].

== Generating the MAIN site

http://grails.org[http://grails.org]

----
./gradlew :main:runShadow
----

The output can be found in the `main/build/site` directory.

== Generating the GORM site

http://gorm.grails.org[http://gorm.grails.org]

----
./gradlew :gorm:runShadow
----

The output can be found in the `gorm/build/site` directory.

== Generating the GUIDES site

https://guides.grails.org[https://guides.grails.org]

----
./gradlew :guides:runShadow
----

The output can be found in the `guides/build/site` directory.

== Grails Navigation Plugin

The project generates a Grails Plugin and a Groovy library. Those
artefacts are used to create Grails applications (e.g. Grails Plugin, Grails App Forge) wiht the look and feel of
the grails Website.

Distributions are served by Bintray:

- https://bintray.com/grails/plugins/grails-navigation[grails-navigation]
- https://bintray.com/grails/plugins/grails-navigation-core[grails-navigation-core]
